import os
import glob
import re
import pandas as pd
import logging
from typing import List, Dict, Tuple
from multiprocessing import Pool, cpu_count


def get_space_topics() -> Tuple[List[str], Dict[str, str]]:
    """Load CSO topics and prepare substitutions dictionary.

    This function reads the CSO concepts from a CSV file and creates a mapping for
    multi-word topics to their underscore-connected versions.

    Returns:
        Tuple[List[str], Dict[str, str]]: A tuple containing:
            - List of all CSO topics, sorted by length in descending order
            - Dictionary mapping space-separated topics to underscore versions
    """
    cso_df = pd.read_csv('cso_label/concepts.csv')
    substitutions = {}
    topics = sorted(
        cso_df['Label'].dropna().astype(str).str.lower().unique(),
        key=len,
        reverse=True
    )
    for topic in topics:
        if ' ' in topic:
            substitutions[topic] = topic.replace(" ", "_")
    return topics, substitutions


def process_line(line: str, topics: List[str], substitutions: Dict[str, str]) -> Tuple[str, List[str]]:
    """Process and clean a line of text.

    This function takes a line of text and performs several cleaning operations:
    1. Handles UTF-8 encoding/decoding
    2. Converts Unicode escape sequences
    3. Removes special characters
    4. Normalizes whitespace
    5. Replaces topic phrases with underscore-connected versions

    Args:
        line (str): The input text line to process
        topics (List[str]): List of CSO topics to check for
        substitutions (Dict[str, str]): Mapping of space-separated topics to underscore versions

    Returns:
        Tuple[str, List[str]]: A tuple containing:
            - The processed text line
            - List of topics that were replaced in the line
    """
    line = line.encode().decode('utf-8', errors='ignore')
    line = re.sub(r'\\u[0-9a-fA-F]{4}', lambda m: chr(int(m.group(0)[2:], 16)), line)
    line = re.sub(r'[^\w\s-]', ' ', line)
    line = re.sub(r'\s+', ' ', line.strip())

    to_change = [topic for topic in substitutions if topic in line.lower()]
    for topic in to_change:
        pattern = re.compile(re.escape(topic), re.IGNORECASE)
        line = pattern.sub(substitutions[topic], line)

    line = re.sub(r'#r##n##r##n#', '\n', line)
    return line.strip(), to_change


def process_file(input_file: str) -> None:
    """Process a single file by reading, cleaning, and writing to output.

    This function processes an input file by:
    1. Reading the file line by line
    2. Cleaning and processing each line using process_line()
    3. Writing processed lines to an output file
    4. Collecting sample changes for demonstration

    The output file name is generated by replacing "abstracts_part" with 
    "abstracts_filtered_part" in the input filename.

    Args:
        input_file (str): Path to the input file to process

    Returns:
        None: The function writes output to a file and prints sample changes
    """
    logging.info(f"Started processing: {input_file}")
    output_file = input_file.replace("abstracts_part", "abstracts_filtered_part")
    topics, substitutions = get_space_topics()

    before_after_samples = []
    sample_count = 0
    cnt = 0

    with open(input_file, encoding='utf-8') as infile, open(output_file, "w+", encoding="utf-8") as outfile:
        for line in infile:
            new_line, changed_topics = process_line(line, topics, substitutions)
            outfile.write(new_line + '\n')
            cnt += 1
            if changed_topics and sample_count < 2:
                before_after_samples.append((line.strip(), new_line, changed_topics))
                sample_count += 1

    logging.info(f"Finished processing {input_file} ({cnt} lines)")

    print(f"\n--- Sample Changes in {input_file} ---")
    for i, (before, after, topics) in enumerate(before_after_samples, 1):
        print(f"\nSample {i}:")
        print(f"Before: {before}")
        print(f"After:  {after}")
        print(f"Concepts Replaced: {', '.join(topics)}")


def get_dataset_files(base_dir: str, patterns: List[str]) -> List[str]:
    """Collect all matching files from specified wildcard patterns.

    This function takes a base directory and a list of file patterns, and returns
    a list of all files that match any of the patterns. It uses glob to expand
    wildcards in the patterns.

    Args:
        base_dir (str): Base directory to search in
        patterns (List[str]): List of file patterns to match (can include wildcards)

    Returns:
        List[str]: List of paths to all matching files

    Example:
        >>> base_dir = "data"
        >>> patterns = ["data/*.txt", "data/*/*.csv"]
        >>> files = get_dataset_files(base_dir, patterns)
    """
    all_files = []
    for pattern in patterns:
        matched = glob.glob(pattern)
        if not matched:
            logging.warning(f"No files found for pattern: {pattern}")
        all_files.extend(matched)
    return all_files


def main()->None:
    """Main function to orchestrate the data cleaning process.

    This function:
    1. Sets up logging configuration
    2. Defines input file patterns to process
    3. Collects dataset files matching the patterns
    4. Processes files in parallel using multiprocessing

    The function processes academic paper abstracts by:
    - Reading input files containing raw abstracts
    - Cleaning and standardizing the text
    - Replacing space-separated CSO topics with underscore versions
    - Writing processed output to new files

    Returns:
        None: Results are written to output files in the same directory
    """
    logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)

    base_dir = "paper_dataset"
    patterns = [
        os.path.join(base_dir, "abstracts_part_v1_2.txt"),
        os.path.join(base_dir, "abstracts_part_v1_3.txt"),
        os.path.join(base_dir, "abstracts_part_v1_4.txt"),
    ]

    dataset_files = get_dataset_files(base_dir, patterns)

    if not dataset_files:
        logging.warning("No files to process. Exiting.")
        return

    # Use up to number of cores or number of files
    num_processes = min(len(dataset_files), cpu_count())
    logging.info(f"Processing {len(dataset_files)} files with {num_processes} processes.")

    with Pool(processes=num_processes) as pool:
        pool.map(process_file, dataset_files)


if __name__ == "__main__":
    main()
